name: Deploy Backend to ECS

on:
  push:
    branches:
      - fix-auth-config
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ECS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ECS }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: questevent-backend
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG

      - name: Deploy to ECS (Force new deployment)
        run: |
          aws ecs update-service \
          --cluster questevent-cluster \
          --service questevent-backend-task-service-w2yv7ryu \
          --force-new-deployment

