name: Deploy Backend to ECS

on:
  push:
    branches:
      - master
      - fix-auth-config

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ECS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ECS }}
          aws-region: ap-south-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build app
        run: ./gradlew clean build -x test

      - name: Build and push Docker image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/questevent-backend:latest .
          docker push ${{ steps.login-ecr.outputs.registry }}/questevent-backend:latest

      - name: Render task definition
        id: render
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          container-name: questevent
          image: ${{ steps.login-ecr.outputs.registry }}/questevent-backend:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render.outputs.task-definition }}
          cluster: questevent-cluster
          service: questevent-backend-task-service-w2yv7ryu
          wait-for-service-stability: true
